artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/SheershKaushik/Datasets/raw/refs/heads/main/TMDB.csv.zip
  local_data_file: artifacts/data_ingestion/TMDB.csv.zip
  unzip_dir: artifacts/data_ingestion

